### ISSUE TITLE
Invalid CodiceFiscale

### ISSUE THREAD

**Issue by VerVera** [Marketto/codice-fiscale-utils#102]
We are not able to validate one of our client with code  "RCCLGU63T27I560K"
```js
        console.log(Validator.codiceFiscale('RCCLGU63T27I560K').valid)  //output: false , expected: true
        console.log(Parser.cfToBirthPlace('RCCLGU63T27I560K'))//output: null, expected: SECONDIGLIANO
        console.log(Parser.placeToCf('SECONDIGLIANO')) //output: I560
        console.log(Validator.codiceFiscale('RCCLGU63T27I560K').matchBirthPlace('SECONDIGLIANO')) // output: true
```

**Comment by Marketto** [comment]
The Provided CF is valid for the Agenzia delle Entrate while Secondigliano became part of Napoli city in 1926 and the provided CF birth year is in 1963; probably due to the introduction of CF back in 1973: I will skip date/city validation for birth dates before 29 sept. 1973.
