### ISSUE TITLE
Belfiore.findName("Sud Sudan")  Returns null incorrectly

### ISSUE THREAD

**Issue by allycdafc** [Marketto/codice-fiscale-utils#108]
**Environment:**
- OS: Windows 11
- Browser name and version/Node version:   Node.js v20.12.2.

**Platform**
[ ] nodeJs
[ ] Web/Browser

**Issue description:**
Describe the problem

When running the Belfiore.findName("Sud Sudan") 
This is due to an error in scanDataSourceIndex that does not properly handle the last element when the "|" is not present

**Steps to reproduce the problem**:
Run test case 
`		
describe("Belfiore.findByName()", () => {
			it("Should return Sud Sudan", () => {
				const place = Belfiore.findByName("Sud Sudan");
				expect(place).to.be.ok;
				if (place) {
					place.name.should.be.equalIgnoreCase("SUD SUDAN");
				}
			});
		}); 
`

Add Pipe to end of cities-countries.ts after Sud Sudan and the test then passes		

**Expected behavior**
 Belfiore.findByName("Sud Sudan") should return the Sud Sudan object

**Screenshots**

**Additional context**
Additional test shows that "Quero Vas" also does not return correctly

**Comment by Marketto** [comment]
Resolver with release 2.2.1
