### ISSUE TITLE
Fail firstName validation on multiple names

### ISSUE THREAD

**Issue by dvero23** [Marketto/codice-fiscale-utils#111]
**Environment:**
- OS: Windows
- Browser name and version/Node version:  Chrome, Node v18.17.1

**Issue description:**
firstName validation fails when checking multiple names (3 names) despite the fiscal code tested [here](https://telematici.agenziaentrate.gov.it/VerificaCF/Scegli.do?parameter=verificaCfPf) being valid.
If I insert only the first firstName, it passes (but instead fails [here](https://telematici.agenziaentrate.gov.it/VerificaCF/Scegli.do?parameter=verificaCfPf)).

**Expected behavior**
Passing firstName validation.

**Screenshots**
![image](https://github.com/Marketto/codice-fiscale-utils/assets/106613927/d207a04d-9b55-4cc4-ac25-1c06186b8318)
![image](https://github.com/Marketto/codice-fiscale-utils/assets/106613927/65e781e3-4956-415b-8cfa-dcb8d8753a58)

**Additional context**
Let me know if you need additional info, thanks.

**Comment by Marketto** [comment]
Will be fixed soon
