### ISSUE TITLE
Codice fiscale non riconoscciuto

### ISSUE THREAD

**Issue by Polm90** [Marketto/codice-fiscale-utils#113]
Buongiorno,
il seguente codice fiscale ZHZLDY77B48Z138H è ritenuto non valido dalla libreria, mentre per l'agenzia delle entrate è valido https://telematici.agenziaentrate.gov.it/VerificaCF/VerificaCf.do (ed effettivamente è quello riportato sul tesserino sanitario della persona in oggetto).

Usando altri sistemi di verifica di codice fiscale, parrebbe che il "problema" sia che l'Ucraina è riconosciuta solo per persone nate dopo il 24/08/1991

**Comment by Marketto** [comment]
Will be fixed soon
