### ISSUE TITLE
Codice fiscale non riconosciuto

### ISSUE THREAD

**Issue by Polm90** [Marketto/codice-fiscale-utils#119]
Sto usando la versione 2.2.2.
Il seguente codice fiscale non è riconosciuto: KCRCHR97E71Z149M per la persona Kucera Chiara

**Comment by Marketto** [comment]
L'upgrade alla versione 3 dovrebbe risolvere, cercherò di rilasciare una hotfix per la v2 quanto prima

**Comment by Polm90** [comment]
Grazie, anche perchè ho qualche problema a passare alla versione 3, quindi un aggiornamento della 2 sarebbe utile

**Comment by Marketto** [comment]
Risolto con la 2.2.3
