### ISSUE TITLE
Error during installation (missing dependency)

### ISSUE THREAD

**Issue by greguz** [Marketto/codice-fiscale-utils#45]
**Environment:**
- OS: Arch Linux 5.5.2-arch1-1
- Node version: v10.16.3

**Platform**
[x] nodeJs
[ ] Web/Browser

**Issue description:**
[This require](https://github.com/Marketto/codice-fiscale-utils/blob/275d0ffbc359625c110f6ea92872d91c1b3d6c7a/scripts/post-install.js#L1
) uses a devDependency that may not be present on any environment. This results in an error during dependencies installation.

**Steps to reproduce the problem**:
Just `npm i @marketto/codice-fiscale-utils` on a new project (no local or global deps installed).

**Expected behavior**
No errors during installation.

**Comment by greguz** [comment]
Hi @Marketto, why did you close this issue? I still have the install error with your package. You can easily fix this by adding `colors` as dependency.

**Comment by Marketto** [comment]
> Hi @Marketto, why did you close this issue? I still have the install error with your package. You can easily fix this by adding `colors` as dependency.

Hi, dependency was removed, the script was configured to be executed before install as a mistake. V2.0.0 is ready with semver and fixes.
