### ISSUE TITLE
IE compatibility problem

### ISSUE THREAD

**Issue by DanielePizzi** [Marketto/codice-fiscale-utils#51]
**Environment:**
- Interne explorer 11 
- Angular 8

**Issue description:**
Utilizzando la libreria in oggetto su internet explorer 11, quest'ultima non sembra supportata. Nello specifico utilizzandola come suggerito nella sezione Documentation, il browser restituisce errore di sintassi. Una prova che ho fatto è stata provare a utilizzarla come:

- var Parser = codiceFiscaleUtils.Parser 

al posto di 

- const { Parser } = codiceFiscaleUtils.

**Expected behavior**
Compatibilità con Internet Explorer

**Comment by Marketto** [comment]
Il codice di esempio è ES6, dovrebbe essere convertito da angular o da un transpiler opportunamente configurato per il browser su cui si vuol far girare l'app; la libreria è disponibile in ESNext e ES2015 per garantire la massima compatibilità.
