### ISSUE TITLE
Problem using with isolatedModules

### ISSUE THREAD

**Issue by psenderos** [Marketto/codice-fiscale-utils#66]
**Platform**
[ ] nodeJs
[X ] Web/Browser

**Issue description:**
I encounter a problem when using with isolatedModules set to true.

`
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.  TS1205

     7 | export {
     8 |     BelfioreConnector,
     9 |     BelfiorePlace,
        |     ^
    10 | };
`

**Steps to reproduce the problem**:
1. Just install it with the flag isolatedModule set to true in your tsconfig file
2. Try to start the application

**Comment by jscheid** [comment]
Ciao @Marketto, could you check to see if #72 helps?
