### ISSUE TITLE
No more installable/upgradeable Node.js v18 or v19

### ISSUE THREAD

**Issue by lapoguidi** [Marketto/codice-fiscale-utils#89]
**Environment:**
- OS: Windows
- Browser name and version/Node version: Chrome, Edge/Node.js v18.12.1 

**Platform**
[X] nodeJs
[X] Web/Browser

**Issue description:**
When I try to install or upgrade using Node.js v18.12.1, I receive this message:
```
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
This error happened while installing a direct dependency of E:\laragon\www\eventbox
Your Node version is incompatible with "registry.npmjs.org/@marketto/codice-fiscale-utils/2.1.1".
Expected version: ^16.0.0
Got: v18.12.1
This is happening because the package's manifest has an engines.node field specified.
```
Maybe there are some issues using it with modern Node.js?

**Steps to reproduce the problem**:
1. With Node.js outside v16, run npm install @marketto/codice-fiscale-utils
2. See error

**Expected behavior**
Maybe it should work also in Node.js v18 or v19?
I used v2.1.0 with Node.js v18 without tangible issues until now.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by aoor9** [comment]
That's because the `engine` property in package.json has been set since v2.1.1 (the day before you posted this issue), and its value says only v16 is supported. To include v18 too, it should be changed like this:
```
"engines": {
   "node": ">=16.x.x <=18.x.x",
}
```

**Comment by lapoguidi** [comment]
Thanks for the reply.
I have already used the workaround just changing to ">=16", anyway I opened the issue just to report it to the author and hope for the correction, if there are no reasons why it currently cannot be installed with Nodejs versions higher than v16.

**Comment by Marketto** [comment]
Hey, sorry for late reply, I'll manage it asap

**Comment by lapoguidi** [comment]
Nice to hear that!
