### ISSUE TITLE
Codice fiscale non valido

### ISSUE THREAD

**Issue by valepe** [Marketto/codice-fiscale-utils#90]
Una persona non riesce a registrarsi sul nostro sito perché la validazione del Codice Fiscale risulta non valido.
Ho provato anche in altri siti di validazione con medesimo risultato ma il validatore dell'Agenzie delle Entrate riporta Codice Fiscale valido.

Il codice fiscale che fallisce termina con Z1N9H

Sospetto che il problema si presenti con il calcolo dell'omocodia.

Grazie

**Comment by condesully** [comment]
Penso sia difficile per l'autore della libreria fixare il problema se non fornisce un caso studio completo e riproducibile.
Detto questo @valepe le suggerisco di attenersi allo schema che GitHub fornisce  per l'apertura dei ticket e di scrivere (possibilmente) in inglese

**Comment by valepe** [comment]
Se l'autore vuole posso comunicare in privato il codice fiscale che genera l'errore. 
Per l'inglese lo ritengo superfluo visto il contesto

**Comment by Marketto** [comment]
Ciao @valepe purtroppo senza il codice fiscale è difficile risalire al problema, data la complessità dei controlli. Se potessi fornirmelo in privato sarebbe fantastico. Grazie
Ho verificato e pare che la libreria interpreti correttamente Z1N9 -> Z129 come Romania
