### ISSUE TITLE
Missing county code KAZAKISTAN-"Z152"	

### ISSUE THREAD

**Issue by VerVera** [Marketto/codice-fiscale-utils#97]
Validator return **false** for people with code Z152
```
console.log(Validator.codiceFiscale('KSTVRI81C59Z152B').valid)// FALSE
console.log(Parser.cfToBirthPlace('KSTVRI81C59Z152B')) //NULL
```

**Comment by VerVera** [comment]
http://www.elesh.it/storiastati/storia_stato.asp?codcat=Z152#:~:text=Stati%20Esteri%20%2D%20Storia%20dello%20Stato%20KAZAKISTAN%20(Codice%20Catastale%20Z152)

**Comment by Marketto** [comment]
Hi @VerVera I'll check official country lists to understand why it's missing
I checked the CF you provided on the official Agenzia delle Entrate service and it looks it's not a valid code; I'm pretty sure Kazakistan was still Sovietic Union in 1981
Can you provide any official source for that Belfiore code? (Z152)
I sent an email to istat support asking more details about Z152
